# Generated by Django 5.0 on 2024-01-03 03:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Actividades', '0006_alter_actividadmodel_fecha_inicio'),
        ('Docentes', '0002_docentesmodel_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='bitacoraModelCabecera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Docentes.docentesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='bitacoraModelDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='evidencias')),
                ('horas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='horas_relacionadas', to='Actividades.actividadmodel')),
                ('nombre_actividad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actividades_relacionadas', to='Actividades.actividadmodel')),
            ],
        ),
    ]
